services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: samuelokuboyejo
      POSTGRES_PASSWORD: opeyemi04
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5322:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
